In [1]:
import sys
import importlib
sys.path.append('../')

from IPython.display import display, Math, Latex

# From data_preparation classes
from src.finance_ml.data_preparation.data_preparation import DataLoader

from src.finance_ml.denoising.denoising import Denoising
from src.finance_ml.indicators.indicators import Indicators
from src.finance_ml.volatility.volatility import Volatility

# Import required packages
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import math

In [2]:
data=np.random.normal(0, 1, size=(6,6))

In [3]:
data

array([[ 1.98047486,  0.25352827,  0.31135052,  0.28426903, -0.28906795,
        -1.94964951],
       [ 1.05775512,  1.06618689,  0.77720686,  1.49616676, -0.25186409,
        -0.25372497],
       [-0.23096608, -1.82591719, -1.15421273,  1.03336066,  1.59250056,
         0.07034285],
       [ 0.46598494, -0.65340986, -0.71835426, -1.90281923,  1.40891275,
        -0.53263571],
       [ 0.25266527, -0.32920236, -0.71530303, -1.93518178,  0.39977796,
         0.31323073],
       [ 0.05565749, -0.80193969,  0.83375937,  0.37389877, -0.3063599 ,
         1.22296876]])

In [4]:
# Instanciate the Denoising transformer
# 'fit_transform()' calculates Correlation, Covariance, EigenValues and 
#     EigenVectors of denoised covariance matrix
denoise_processor = Denoising(detoning=False)

denoised_obj = denoise_processor.run_denoising(data)

In [5]:
# Retrieves non-denoised Covariance and Correlation Matrices
cov0 = denoised_obj.get_cov_original
corr0 = denoised_obj.get_corr_original
corr1 = denoised_obj.get_corr_denoised
np.set_printoptions(formatter={'float_kind':'{:f}'.format})

In [6]:
cov0

array([[0.648122, 0.597344, 0.326704, 0.188051, -0.398144, -0.714527],
       [0.597344, 0.967768, 0.559442, 0.222539, -0.616212, -0.412061],
       [0.326704, 0.559442, 0.736443, 0.609873, -0.678807, 0.033506],
       [0.188051, 0.222539, 0.609873, 2.164425, -0.421134, -0.023790],
       [-0.398144, -0.616212, -0.678807, -0.421134, 0.766940, 0.044076],
       [-0.714527, -0.412061, 0.033506, -0.023790, 0.044076, 1.107062]])

In [7]:
corr0

array([[1.000000, 0.754242, 0.472886, 0.158772, -0.564718, -0.843538],
       [0.754242, 1.000000, 0.662674, 0.153762, -0.715260, -0.398098],
       [0.472886, 0.662674, 1.000000, 0.483057, -0.903225, 0.037108],
       [0.158772, 0.153762, 0.483057, 1.000000, -0.326865, -0.015369],
       [-0.564718, -0.715260, -0.903225, -0.326865, 1.000000, 0.047834],
       [-0.843538, -0.398098, 0.037108, -0.015369, 0.047834, 1.000000]])

In [8]:
corr1

array([[1.000000, 0.544465, 0.530427, 0.337057, -0.539527, -0.370468],
       [0.544465, 1.000000, 0.537554, 0.341586, -0.546777, -0.375446],
       [0.530427, 0.537554, 1.000000, 0.332778, -0.532678, -0.365765],
       [0.337057, 0.341586, 0.332778, 1.000000, -0.338488, -0.232424],
       [-0.539527, -0.546777, -0.532678, -0.338488, 1.000000, 0.372041],
       [-0.370468, -0.375446, -0.365765, -0.232424, 0.372041, 1.000000]])

In [9]:
# Instanciate the Denoising transformer
# 'fit_transform()' calculates Correlation, Covariance, EigenValues and 
#     EigenVectors of denoised covariance matrix
denoise_processor = Denoising(detoning=True,market_component=2)

detoned_and_denoised_obj = denoise_processor.run_denoising(data)

In [10]:
# Retrieves non-denoised Covariance and Correlation Matrices
detoned_and_denoised_cov0 = detoned_and_denoised_obj.get_cov_original
detoned_and_denoised_corr0 = detoned_and_denoised_obj.get_corr_original
detoned_and_denoised_corr1 = detoned_and_denoised_obj.get_corr_denoised
np.set_printoptions(formatter={'float_kind':'{:f}'.format})

In [11]:
detoned_and_denoised_cov0

array([[0.648122, 0.597344, 0.326704, 0.188051, -0.398144, -0.714527],
       [0.597344, 0.967768, 0.559442, 0.222539, -0.616212, -0.412061],
       [0.326704, 0.559442, 0.736443, 0.609873, -0.678807, 0.033506],
       [0.188051, 0.222539, 0.609873, 2.164425, -0.421134, -0.023790],
       [-0.398144, -0.616212, -0.678807, -0.421134, 0.766940, 0.044076],
       [-0.714527, -0.412061, 0.033506, -0.023790, 0.044076, 1.107062]])

In [12]:
detoned_and_denoised_corr0

array([[1.000000, 0.754242, 0.472886, 0.158772, -0.564718, -0.843538],
       [0.754242, 1.000000, 0.662674, 0.153762, -0.715260, -0.398098],
       [0.472886, 0.662674, 1.000000, 0.483057, -0.903225, 0.037108],
       [0.158772, 0.153762, 0.483057, 1.000000, -0.326865, -0.015369],
       [-0.564718, -0.715260, -0.903225, -0.326865, 1.000000, 0.047834],
       [-0.843538, -0.398098, 0.037108, -0.015369, 0.047834, 1.000000]])

In [13]:
detoned_and_denoised_corr1

array([[1.000000, -0.208379, -0.215275, -0.302144, 0.210942, 0.302605],
       [-0.208379, 1.000000, -0.211829, -0.307928, 0.207160, 0.301786],
       [-0.215275, -0.211829, 1.000000, -0.295996, 0.214220, 0.303332],
       [-0.302144, -0.307928, -0.295996, 1.000000, 0.304051, -0.999961],
       [0.210942, 0.207160, 0.214220, 0.304051, 1.000000, -0.302352],
       [0.302605, 0.301786, 0.303332, -0.999961, -0.302352, 1.000000]])

In [14]:
#giving market component value greater than number of features in correlation matrix, algorithm must be give an error
denoise_processor = Denoising(detoning=True,market_component=7)

denoised_obj = denoise_processor.run_denoising(data)

ValueError: Parameter market_component must less than number of features in denoised correlation matrix

In [ ]:
#giving market component value decimal value, algorithm must be give an error
denoise_processor = Denoising(detoning=True,market_component=2.5)

denoised_obj = denoise_processor.run_denoising(data)

ValueError: Denoising Class - Parameter market_component must be int and greater than 1

In [ ]:
detoned_and_denoised_corr1

array([[1.000000, 0.191322, 0.372534, 0.477484, -0.300662, 0.195673],
       [0.191322, 1.000000, -0.280185, 0.080697, -0.300584, -0.468665],
       [0.372534, -0.280185, 1.000000, -0.192411, -0.005850, -0.351107],
       [0.477484, 0.080697, -0.192411, 1.000000, 0.551992, 0.077088],
       [-0.300662, -0.300584, -0.005850, 0.551992, 1.000000, -0.347528],
       [0.195673, -0.468665, -0.351107, 0.077088, -0.347528, 1.000000]])

In [ ]:
corr1

array([[1.000000, -0.229161, -0.356559, -0.313743, 0.148056, -0.184552],
       [-0.229161, 1.000000, 0.475365, 0.020840, 0.281415, 0.421666],
       [-0.356559, 0.475365, 1.000000, 0.284961, 0.013227, 0.375243],
       [-0.313743, 0.020840, 0.284961, 1.000000, -0.446713, 0.027045],
       [0.148056, 0.281415, 0.013227, -0.446713, 1.000000, 0.209381],
       [-0.184552, 0.421666, 0.375243, 0.027045, 0.209381, 1.000000]])