In [1]:
import sys
import importlib
sys.path.append('../')

from IPython.display import display, Math, Latex

# From data_preparation classes
from src.finance_ml.data_preparation.data_preparation import DataLoader

from src.finance_ml.denoising.denoising import Denoising
from src.finance_ml.indicators.indicators import Indicators
from src.finance_ml.volatility.volatility import Volatility

# Import required packages
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import math

In [2]:
data=np.random.normal(0, 1, size=(6,6))

In [3]:
data

array([[ 1.62193678,  1.45788498, -0.92748884,  1.08301399, -0.22002977,
        -1.01225953],
       [-0.1193862 , -1.13001051,  1.02256465,  0.30373064,  0.75113836,
         0.81874208],
       [-0.57623543,  0.30806414,  0.53093642, -1.5775822 ,  0.46733018,
         1.99004151],
       [-0.76738872, -0.47010582,  0.1253657 ,  0.17572943,  0.67310587,
        -0.28084103],
       [ 0.22741268,  0.71238576, -0.50682599,  1.37415361,  0.52285345,
         0.5315758 ],
       [-1.03906297, -2.1822949 ,  1.00254024, -0.00412916,  0.28095681,
        -0.10751553]])

In [4]:
# Instanciate the Denoising transformer
# 'fit_transform()' calculates Correlation, Covariance, EigenValues and 
#     EigenVectors of denoised covariance matrix
denoise_processor = Denoising(detoning=False)

denoised_obj = denoise_processor.run_denoising(data)

In [5]:
# Retrieves non-denoised Covariance and Correlation Matrices
cov0 = denoised_obj.get_cov_original
corr0 = denoised_obj.get_corr_original
corr1 = denoised_obj.get_corr_denoised
np.set_printoptions(formatter={'float_kind':'{:f}'.format})

In [6]:
cov0

array([[0.925245, 0.994084, -0.609970, 0.591743, -0.227223, -0.445433],
       [0.994084, 1.740945, -0.936179, 0.389901, -0.208937, -0.124189],
       [-0.609970, -0.936179, 0.641247, -0.498336, 0.161369, 0.403415],
       [0.591743, 0.389901, -0.498336, 1.073433, -0.094156, -0.748708],
       [-0.227223, -0.208937, 0.161369, -0.094156, 0.123035, 0.205231],
       [-0.445433, -0.124189, 0.403415, -0.748708, 0.205231, 1.080235]])

In [7]:
corr0

array([[1.000000, 0.783254, -0.791894, 0.593768, -0.673459, -0.445548],
       [0.783254, 1.000000, -0.886041, 0.285217, -0.451449, -0.090559],
       [-0.791894, -0.886041, 1.000000, -0.600650, 0.574505, 0.484708],
       [0.593768, 0.285217, -0.600650, 1.000000, -0.259088, -0.695290],
       [-0.673459, -0.451449, 0.574505, -0.259088, 1.000000, 0.562951],
       [-0.445548, -0.090559, 0.484708, -0.695290, 0.562951, 1.000000]])

In [8]:
corr1

array([[1.000000, 0.581350, -0.628439, 0.559467, -0.570679, -0.539324],
       [0.581350, 1.000000, -0.583758, 0.519690, -0.530105, -0.500979],
       [-0.628439, -0.583758, 1.000000, -0.561785, 0.573043, 0.541557],
       [0.559467, 0.519690, -0.561785, 1.000000, -0.510151, -0.482121],
       [-0.570679, -0.530105, 0.573043, -0.510151, 1.000000, 0.491783],
       [-0.539324, -0.500979, 0.541557, -0.482121, 0.491783, 1.000000]])

In [9]:
# Instanciate the Denoising transformer
# 'fit_transform()' calculates Correlation, Covariance, EigenValues and 
#     EigenVectors of denoised covariance matrix
denoise_processor = Denoising(detoning=True,market_component=2)

detoned_and_denoised_obj = denoise_processor.run_denoising(data)

In [10]:
# Retrieves non-denoised Covariance and Correlation Matrices
detoned_and_denoised_cov0 = detoned_and_denoised_obj.get_cov_original
detoned_and_denoised_corr0 = detoned_and_denoised_obj.get_corr_original
detoned_and_denoised_corr1 = detoned_and_denoised_obj.get_corr_denoised
np.set_printoptions(formatter={'float_kind':'{:f}'.format})

In [11]:
detoned_and_denoised_cov0

array([[0.925245, 0.994084, -0.609970, 0.591743, -0.227223, -0.445433],
       [0.994084, 1.740945, -0.936179, 0.389901, -0.208937, -0.124189],
       [-0.609970, -0.936179, 0.641247, -0.498336, 0.161369, 0.403415],
       [0.591743, 0.389901, -0.498336, 1.073433, -0.094156, -0.748708],
       [-0.227223, -0.208937, 0.161369, -0.094156, 0.123035, 0.205231],
       [-0.445433, -0.124189, 0.403415, -0.748708, 0.205231, 1.080235]])

In [12]:
detoned_and_denoised_corr0

array([[1.000000, 0.783254, -0.791894, 0.593768, -0.673459, -0.445548],
       [0.783254, 1.000000, -0.886041, 0.285217, -0.451449, -0.090559],
       [-0.791894, -0.886041, 1.000000, -0.600650, 0.574505, 0.484708],
       [0.593768, 0.285217, -0.600650, 1.000000, -0.259088, -0.695290],
       [-0.673459, -0.451449, 0.574505, -0.259088, 1.000000, 0.562951],
       [-0.445548, -0.090559, 0.484708, -0.695290, 0.562951, 1.000000]])

In [13]:
detoned_and_denoised_corr1

array([[1.000000, -0.211187, 0.177321, -0.258462, 0.223756, 0.496663],
       [-0.211187, 1.000000, 0.209734, -0.310026, 0.258548, 0.178198],
       [0.177321, 0.209734, 1.000000, 0.256618, -0.222272, -0.502660],
       [-0.258462, -0.310026, 0.256618, 1.000000, 0.345607, -0.863649],
       [0.223756, 0.258548, -0.222272, 0.345607, 1.000000, 0.089115],
       [0.496663, 0.178198, -0.502660, -0.863649, 0.089115, 1.000000]])

In [14]:
#giving market component value greater than number of features in correlation matrix, algorithm must be give an error
denoise_processor = Denoising(detoning=True,market_component=7)

denoised_obj = denoise_processor.run_denoising(data)

ValueError: Parameter market_component must less than the number of features in denoised correlation matrix: 6

In [ ]:
#giving market component value decimal value, algorithm must be give an error
denoise_processor = Denoising(detoning=True,market_component=2.5)

denoised_obj = denoise_processor.run_denoising(data)

ValueError: Denoising Class - Parameter market_component must be int and greater than 1