In [1]:
import sys
import importlib
sys.path.append('../')

from IPython.display import display, Math, Latex

# From data_preparation classes
from src.finance_ml.data_preparation.data_preparation import DataLoader

from src.finance_ml.denoising.denoising import Denoising
from src.finance_ml.indicators.indicators import Indicators
from src.finance_ml.volatility.volatility import Volatility

# Import required packages
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import math

In [2]:
data=np.random.normal(0, 1, size=(6,6))

In [3]:
data

array([[ 1.53572554,  0.0667005 ,  1.8234282 ,  0.07305898, -1.10695953,
         1.01001688],
       [-0.26925907,  0.74008919,  0.52182369,  0.54209408, -0.85096945,
         0.03074859],
       [ 0.26888693,  0.53971422,  0.78754307, -0.73511047,  0.23840526,
         0.3441936 ],
       [-0.17907365, -0.52701678, -0.60309171,  0.61496152,  0.28109283,
         1.37465629],
       [-0.50306857,  0.88440266, -1.7722701 , -0.66637137, -0.45389501,
        -0.6669001 ],
       [ 0.49903174, -0.39587281,  0.85160639,  2.06751851,  0.06111044,
        -0.59058588]])

In [4]:
# Instanciate the Denoising transformer
# 'fit_transform()' calculates Correlation, Covariance, EigenValues and 
#     EigenVectors of denoised covariance matrix
denoise_processor = Denoising(detoning=False)

denoised_obj = denoise_processor.run_denoising(data)

In [5]:
# Retrieves non-denoised Covariance and Correlation Matrices
cov0 = denoised_obj.get_cov_original
corr0 = denoised_obj.get_corr_original
corr1 = denoised_obj.get_corr_denoised
np.set_printoptions(formatter={'float_kind':'{:f}'.format})

In [6]:
cov0

array([[0.546534, -0.158921, 0.786691, 0.119619, -0.157109, 0.218290],
       [-0.158921, 0.354990, -0.200919, -0.427191, -0.149901, -0.226411],
       [0.786691, -0.200919, 1.603161, 0.379898, -0.219348, 0.315182],
       [0.119619, -0.427191, 0.379898, 1.067444, 0.092590, -0.113711],
       [-0.157109, -0.149901, -0.219348, 0.092590, 0.347244, 0.009863],
       [0.218290, -0.226411, 0.315182, -0.113711, 0.009863, 0.689342]])

In [7]:
corr0

array([[1.000000, -0.360799, 0.840440, 0.156610, -0.360640, 0.355637],
       [-0.360799, 1.000000, -0.266333, -0.693971, -0.426952, -0.457691],
       [0.840440, -0.266333, 1.000000, 0.290406, -0.293986, 0.299817],
       [0.156610, -0.693971, 0.290406, 1.000000, 0.152080, -0.132560],
       [-0.360640, -0.426952, -0.293986, 0.152080, 1.000000, 0.020159],
       [0.355637, -0.457691, 0.299817, -0.132560, 0.020159, 1.000000]])

In [8]:
corr1

array([[1.000000, -0.260032, 0.611276, 0.191281, -0.310529, 0.432516],
       [-0.260032, 1.000000, -0.276328, -0.563766, -0.321969, -0.344337],
       [0.611276, -0.276328, 1.000000, 0.207096, -0.289061, 0.432823],
       [0.191281, -0.563766, 0.207096, 1.000000, 0.324085, 0.284712],
       [-0.310529, -0.321969, -0.289061, 0.324085, 1.000000, -0.075279],
       [0.432516, -0.344337, 0.432823, 0.284712, -0.075279, 1.000000]])

In [9]:
# Instanciate the Denoising transformer
# 'fit_transform()' calculates Correlation, Covariance, EigenValues and 
#     EigenVectors of denoised covariance matrix
denoise_processor = Denoising(detoning=True,market_component=2)

detoned_and_denoised_obj = denoise_processor.run_denoising(data)

In [10]:
# Retrieves non-denoised Covariance and Correlation Matrices
detoned_and_denoised_cov0 = detoned_and_denoised_obj.get_cov_original
detoned_and_denoised_corr0 = detoned_and_denoised_obj.get_corr_original
detoned_and_denoised_corr1 = detoned_and_denoised_obj.get_corr_denoised
np.set_printoptions(formatter={'float_kind':'{:f}'.format})

In [11]:
detoned_and_denoised_cov0

array([[0.546534, -0.158921, 0.786691, 0.119619, -0.157109, 0.218290],
       [-0.158921, 0.354990, -0.200919, -0.427191, -0.149901, -0.226411],
       [0.786691, -0.200919, 1.603161, 0.379898, -0.219348, 0.315182],
       [0.119619, -0.427191, 0.379898, 1.067444, 0.092590, -0.113711],
       [-0.157109, -0.149901, -0.219348, 0.092590, 0.347244, 0.009863],
       [0.218290, -0.226411, 0.315182, -0.113711, 0.009863, 0.689342]])

In [12]:
detoned_and_denoised_corr0

array([[1.000000, -0.360799, 0.840440, 0.156610, -0.360640, 0.355637],
       [-0.360799, 1.000000, -0.266333, -0.693971, -0.426952, -0.457691],
       [0.840440, -0.266333, 1.000000, 0.290406, -0.293986, 0.299817],
       [0.156610, -0.693971, 0.290406, 1.000000, 0.152080, -0.132560],
       [-0.360640, -0.426952, -0.293986, 0.152080, 1.000000, 0.020159],
       [0.355637, -0.457691, 0.299817, -0.132560, 0.020159, 1.000000]])

In [13]:
detoned_and_denoised_corr1

array([[1.000000, 0.067445, -0.374489, -0.045483, 0.354963, -0.387290],
       [0.067445, 1.000000, 0.083866, 0.495584, 0.383128, 0.272447],
       [-0.374489, 0.083866, 1.000000, -0.064997, 0.341521, -0.393288],
       [-0.045483, 0.495584, -0.064997, 1.000000, -0.521498, -0.263125],
       [0.354963, 0.383128, 0.341521, -0.521498, 1.000000, 0.119742],
       [-0.387290, 0.272447, -0.393288, -0.263125, 0.119742, 1.000000]])

In [14]:
#giving market component value greater than number of features in correlation matrix, algorithm must be give an error
denoise_processor = Denoising(detoning=True,market_component=7)

denoised_obj = denoise_processor.run_denoising(data)

ValueError: Parameter market_component must less than number of features in denoised correlation matrix

In [ ]:
#giving market component value decimal value, algorithm must be give an error
denoise_processor = Denoising(detoning=True,market_component=2.5)

denoised_obj = denoise_processor.run_denoising(data)

ValueError: Denoising Class - Parameter market_component must be int and greater than 1

In [ ]:
detoned_and_denoised_corr1

array([[1.000000, 0.191322, 0.372534, 0.477484, -0.300662, 0.195673],
       [0.191322, 1.000000, -0.280185, 0.080697, -0.300584, -0.468665],
       [0.372534, -0.280185, 1.000000, -0.192411, -0.005850, -0.351107],
       [0.477484, 0.080697, -0.192411, 1.000000, 0.551992, 0.077088],
       [-0.300662, -0.300584, -0.005850, 0.551992, 1.000000, -0.347528],
       [0.195673, -0.468665, -0.351107, 0.077088, -0.347528, 1.000000]])

In [ ]:
corr1

array([[1.000000, -0.229161, -0.356559, -0.313743, 0.148056, -0.184552],
       [-0.229161, 1.000000, 0.475365, 0.020840, 0.281415, 0.421666],
       [-0.356559, 0.475365, 1.000000, 0.284961, 0.013227, 0.375243],
       [-0.313743, 0.020840, 0.284961, 1.000000, -0.446713, 0.027045],
       [0.148056, 0.281415, 0.013227, -0.446713, 1.000000, 0.209381],
       [-0.184552, 0.421666, 0.375243, 0.027045, 0.209381, 1.000000]])